sudo: false
os:
- linux
language: haskell
cabal: '2.4'
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
- provider: hackage
  username: "$HACKAGE_USER"
  password: "$HACKAGE_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: CMWK+Gvj5iNuKyJG6lBC35TD3JNHVvjeNOb2etKQWelzkgHEYXwPTW9RsQ2kuLQsgfcG0HnRjtRaIzr3dWucIof+USXN3Jda4sp2fDnQS3/mBXI10QcMVNPdUBaA/L7yTBBFDCHbWSlNO8kNAq3qi08tLX0LoxZDMP7QEZYwUh5lHTBVGku00+FtAMd0JPNJSjx1i8rs5AdpTcKumPXuIucAYE3POM/OtAJhFkhOFGA/Op5690fRhIAh1jwwhnMg5wj2eJCxUNeDzXkg5wJScEVqoAv6xuNJqE8KtiqYt9pPRi4+lzfhil5eeekvP0ntKj/bhMaRUM2+j4E4fHP2wbuny8kQ5LMqslPhBedsYcOejIdRjuTGwAVokGbK1mjsscUPn2VFLFFRTzosFOofUhWZu+3ZRwhny4pSe0JEhIr+5UP8TtTRHMplV+Y61wzHNG37u7QVrwxrywu92+o7Wz/riMOEnUcPWX6IHLRiDPZdD+Knfm0aHZvkeDHC50IFjcObigs0lhsdAcCiHbhAV8QLD6P64mzlfs8VnxJImVadazV1p7as9acdmOUCobmdEl5nZhk5xWcdArgF+kI06HBjs1IhZoq8i7a1yOEc0hyeNiJUMt/uJHxtk+1KrltCZqQseE+3aezHl4fdfvel6r38P2d00A+ztVDLzG17Kgw=
  - secure: FRZyNtQb1GJvJhwwySqmQZGaGJU3BmecCNjRTifHC2MCAK5zqsA9ZVsMiGhprdjZ9cbwd3DGNhGUa6bp8geO0r03px+wlOF5G9JoLrWj96czExJSx+e4zkiuTnetrtUL2tjuntzflgTFA5XhxCM4twFjqsLf4nJ4zrPjO6NklCZ6GwEnQQrPrSJtHzBPbNzBWkiZnKNueXfiV7e+m4CUFU1lFj/cx9Tosp+0zF/FzvwpZiCzcTGn7FycoopYXiM/vFkc2IGjo6O5ceJiwaQgpzG7Uw6ragK4cy6unuFAP/5FpfahvUd6SSm0ckoT/S5P10ff9GJay/cXzNF+4aO3v+NxINoAE5q8nC17LUtKmIjWLcTQLoiH1cu1OyuDsB6kF02uvkIB6dT8pSiLGyzsI5MS1jFAjNpFnqrmh5cLXI1JQgBnR+IKHlP5OeBnxn1z/LGOW3/oT37IoFYBw28vZ0o47qs08mO9BG9CrdusTwTRWAjFXisEvQIidvsZcCAAIWNPfj8xkr6RPmjYlvgbqUoygYSHs8725dDySBCE+3d5X28Xpvj9vzvZ0P1QqI+HwFaVwss0Yy9ScbiD+okBQZY8vyUsrxGbuZOEMgBiUfNwOUhKNMsM9QjeDuzJLSCe025CgE4IJqnnXtz4jxKTWBxJMzpFY80ePL1FZg+ZUy0=
  - secure: e5k8YZ5EW0M0IrsXSRGLV6rpVJdCUBhLx0gnqJ09Em0iwOptZMkiCDh8bsah4vl4F5AG9N8ScdDaf3v8OU8b9zkwpFHGU3bgezBKAUhf3XK8MJueeQdpugZ//il3Vqes96EfGfklKFr96/7FtnjWhc5hv2EOpVhkaBxxEadZUnLjBycZ0z1kdWLpWHSw2EGyS5bykF1dqyAgjYjnL/1Dwe/eDB8ztczhlpVoshuabL7qLhGUC/aLImh68HrnDWCQa4MtPCl4kifWmpld6KgWslQrFljPO7EsBjxrqgffea0Ssn5kF8J+Lc/Isx07j+5oQ4IfBkZK0FohyKA08bIaXq8iDb+90BGJwvpR37KhtG98+2qwqeVsaVSRJe6w4gj0Vh65WGZ5NfJWNZJ4DjfriyjqyuGnwuyK3K2F3tQaaviHnoFBg3dI4yIE1D94YaHT2hq7agpoVA5ZqVb+GyHDdqWrbBOB9u4rj4xXfLnoFqsAR5nEHVneBRNNp2WQsP/AIyb7wzOMcElW7x6nPTy1I3N6RSircdzNb2tGZrtlSvqIPjwWwU42Krhw7a98Z+J4vwxHfyodTkmBEYg8e1SyKbY8nuIDf6nkEO1l8B4iuQtYd8D9qOnWyAUUATO/tE+rFToBlS2SbKk+7aEsV9Umx8mIkOT+ydP2vWfC1YLQjJg=
